We decided the name of our programming language as "Fillme".
We have given this name to our programming language, based on our own names (Filiz & Melin), as it also complies with its purpose.
Fillme is a Linüx based programming system.
We think it is a programming language used in applications such as object recognition and detection systems and counting systems.
For example, on shopping sites, we ask us to indicate which bank credit cards belong to, and we can provide this with "Fillme".
  
Attributes of our programming languages 
 
 İnteger values - > aa 
                    aa: [0-9]* 
 Floating numbers -> bb 
 String characters -> cc: [a-z][A-Z]*
 Boolean values -> correct , incorrect
 Methods ->have Fillme
           have FillmeRecognized
           have FillmeRead
           have FillmeHave
 Loop operators -> unlimited , limited
 Variable names must start with capital letters.
 Comment lines will start with ... (three dots) and end with ... (three dots).
 "Fillme" does not need punctuation much.
 The code starter is << Welcome.
 The statement indicating that the code has ended is >> Godbye.


